# This is a basic workflow to help you get started with Using Checkmarx CxFlow Action-1

name: CxFlow SAST + SCA

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel - this job is specifically configured to use the Checkmarx CxFlow Action
jobs:
 build:
  runs-on: ubuntu-latest
  # Steps require - checkout code, run CxFlow Action, Upload SARIF report (optional)
  steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v2
  # Runs the Checkmarx Scan leveraging the latest version of CxFlow - REFER to Action README for list of inputs
  - name: Checkmarx CxFlow Action
    uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
    with:
      #project: GithubActionTest
      #team: '/CxServer/checkmarxSE'
      #sca_tenant: SCA-Champions  # <-- Insert Checkmarx CxSCA Tenant
      #checkmarx_url: ${{ secrets.CHECKMARX_URL }}
      #checkmarx_username: ${{ secrets.CHECKMARX_USERNAME }}
      #checkmarx_password: ${{ secrets.CHECKMARX_PASSWORD }}
      #checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
      #github_token: ${{ secrets.GH_TOKEN }} # To be stored in GitHub Secrets.
      #params: --checkmarx.scan-preset=High and Medium --cxflow.enabled-vulnerability-scanners=sast --cxflow.enabled-vulnerability-scanners=sca --sca.appUrl=https://sca.scacheckmarx.com --sca.apiUrl=https://api.scacheckmarx.com --sca.accessControlUrl=https://platform.checkmarx.net --sca.tenant=${{ secrets.SCA_TENANT }} --sca.username=${{ secrets.SCA_USERNAME }} --sca.password=${{ secrets.SCA_PASSWORD }} --checkmarx.incremental=false
        project: MFCx_CxFlow_JavaVulnLab-x01 # <-- Insert Checkmarx CxSCA Project Name
        sca_api_url: https://api.scacheckmarx.com
        sca_app_url: https://sca.scacheckmarx.com
        sca_access_control_url: https://platform.checkmarx.net
        sca_tenant: SCA-Champions  # <-- Insert Checkmarx CxSCA Tenant
        sca_username: ${{ secrets.CHECKMARX_SCA_USERNAME }} # To be stored in GitHub Secrets.
        sca_password: ${{ secrets.CHECKMARX_SCA_PASSWORD }} # To be stored in GitHub Secrets.
        break_build: false
        scanners: sca
        bug_tracker: GITHUBPULL
        github_token: ${{ secrets.GH_TOKEN }} # To be stored in GitHub Secrets.
        params: --namespace=${{ github.repository_owner }} --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --merge-id=${{ github.event.number }}
  # Upload the Report for CodeQL/Security Alerts
  - name: Upload SARIF file
    uses: github/codeql-action/upload-sarif@v1
    with:
      sarif_file: cx.sarif

   
